using System;
using System.IO;
using System.Linq;
using RingBuffer.Core;
using RingBuffer.Replay;

namespace RingBuffer.CorpusBuilder;

/// <summary>
/// Writes the conformance corpus: for each declared case, an <c>input.sbe</c>, a
/// <c>case.md</c> and an <c>expected.sbe</c>.
///
/// <c>expected.sbe</c> is produced by replaying through the <b>reference queue</b>,
/// which is obviously correct by inspection and is therefore a legitimate oracle for
/// payload preservation. It is not an oracle for ring semantics — see
/// knowledge/practices/triangulation.md.
///
///   CorpusBuilder --out tests/conformance/corpus [--check]
///
/// <c>--check</c> rebuilds into a temporary directory and diffs, so CI can assert
/// the committed fixtures still match their declarations without rewriting them.
/// </summary>
public static class Program
{
    public static int Main(string[] args)
    {
        string? outDir = null;
        var check = false;

        for (var i = 0; i < args.Length; i++)
        {
            switch (args[i])
            {
                case "--out" when i + 1 < args.Length: outDir = args[++i]; break;
                case "--check": check = true; break;
                default:
                    Console.Error.WriteLine($"CorpusBuilder: unrecognised argument '{args[i]}'");
                    return 2;
            }
        }

        if (outDir is null)
        {
            Console.Error.WriteLine("usage: CorpusBuilder --out <corpusDir> [--check]");
            return 2;
        }

        return check ? Check(outDir) : Build(outDir);
    }

    private static int Build(string outDir)
    {
        Directory.CreateDirectory(outDir);

        foreach (var c in Cases.All)
        {
            var dir = Path.Combine(outDir, c.Name);
            Directory.CreateDirectory(dir);

            var frames = c.Frames();
            using (var s = File.Create(Path.Combine(dir, "input.sbe")))
            {
                foreach (var f in frames)
                {
                    Journal.WriteFrame(s, f);
                }
            }

            var output = new ReplayEngine(() => new ReferenceQueue()).Run(frames);
            using (var s = File.Create(Path.Combine(dir, "expected.sbe")))
            {
                foreach (var f in output)
                {
                    Journal.WriteFrame(s, f);
                }
            }

            File.WriteAllText(Path.Combine(dir, "case.md"),
                $"# {c.Name}\n\n{c.Why}\n\n" +
                $"{frames.Count} frame(s), {frames.Sum(f => f.Length)} payload byte(s).\n\n" +
                "Generated by `tools/CorpusBuilder`. `expected.sbe` was produced by replaying\n" +
                "through the reference queue. **Do not regenerate this to make a test pass** —\n" +
                "a changed `expected.sbe` in a diff is a behaviour change and must be justified\n" +
                "as one. See `knowledge/testing/l4-acceptance-replay.md`.\n");

            Console.WriteLine($"corpus: {c.Name} -- {frames.Count} frame(s)");
        }

        Console.WriteLine($"corpus: {Cases.All.Count} case(s) written to {outDir}");
        return 0;
    }

    private static int Check(string outDir)
    {
        var temp = Directory.CreateTempSubdirectory("corpus-check");
        try
        {
            if (Build(temp.FullName) != 0)
            {
                return 1;
            }

            var differences = 0;
            foreach (var c in Cases.All)
            {
                foreach (var file in new[] { "input.sbe", "expected.sbe" })
                {
                    var committed = Path.Combine(outDir, c.Name, file);
                    var rebuilt = Path.Combine(temp.FullName, c.Name, file);

                    if (!File.Exists(committed))
                    {
                        Console.Error.WriteLine($"corpus: {c.Name}/{file} is missing -- run without --check");
                        differences++;
                        continue;
                    }

                    if (!File.ReadAllBytes(committed).AsSpan().SequenceEqual(File.ReadAllBytes(rebuilt)))
                    {
                        Console.Error.WriteLine(
                            $"corpus: {c.Name}/{file} differs from its declaration in tools/CorpusBuilder/Cases.cs");
                        differences++;
                    }
                }
            }

            if (differences > 0)
            {
                Console.Error.WriteLine(
                    $"\ncorpus: {differences} fixture(s) out of date. If this is intended, rebuild and " +
                    "justify the change in the commit message -- it is a behaviour change.");
                return 1;
            }

            Console.WriteLine($"corpus: {Cases.All.Count} case(s) match their declarations");
            return 0;
        }
        finally
        {
            temp.Delete(recursive: true);
        }
    }
}
