<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>RingBuffer.Codecs.Tests</AssemblyName>
    <RootNamespace>RingBuffer.Codecs.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/RingBuffer.Codecs/RingBuffer.Codecs.csproj" />
    <ProjectReference Include="../../src/RingBuffer.Sbe/RingBuffer.Sbe.csproj" />
    <ProjectReference Include="../RingBuffer.TestSupport/RingBuffer.TestSupport.csproj" />
  </ItemGroup>
</Project>
