using System;

namespace RingBuffer.Replay;

/// <summary>
/// A clock the replay controls. Byte-for-byte diffing is only meaningful if the
/// output is a function of the input alone, so every source of ambient variation
/// has to be closed off — or the diff produces false failures and gets disabled,
/// which is how byte-exact suites usually die.
/// </summary>
public interface IClock
{
    /// <summary>Nanoseconds since the UNIX epoch.</summary>
    long NanosSinceEpoch { get; }
}

/// <summary>
/// Advances by a fixed step on every read. Deterministic given its seed, which is
/// what lets a fixture be regenerated byte-identically.
/// </summary>
public sealed class SeededClock : IClock
{
    private readonly long _stepNanos;
    private long _current;

    public SeededClock(long seed, long stepNanos = 1_000_000)
    {
        // The seed is folded into the start time so two cases with different seeds
        // cannot accidentally produce identical journals.
        _current = 1_700_000_000_000_000_000L + (seed * 1_000_000_000L);
        _stepNanos = stepNanos;
    }

    public long NanosSinceEpoch
    {
        get
        {
            var now = _current;
            _current += _stepNanos;
            return now;
        }
    }
}

/// <summary>A monotonic id source seeded per case, replacing anything GUID-shaped.</summary>
public sealed class SeededIds
{
    private long _next;

    public SeededIds(long seed) => _next = (seed << 32) + 1;

    public long Next() => _next++;
}
