<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RingBuffer.Replay</AssemblyName>
    <RootNamespace>RingBuffer.Replay</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/RingBuffer.Core/RingBuffer.Core.csproj" />
  </ItemGroup>
</Project>
